source 'https://rubygems.org'

ruby '1.8.7'
gem 'rails', '2.3.9'

gem 'truestack_rails',  :git => "git://github.com/caryfitzhugh/truestack_rails.git"
gem 'truestack_client', :git => "git://github.com/caryfitzhugh/truestack_client.git"
