#!/bin/bash
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
fi

cd server
source .rvmrc
bundle install
exec bundle exec rake automation:create_admin_user[$1] MONGOLAB_URI_DEVELOPMENT=$2
