#!/bin/bash
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
fi

cd server
source .rvmrc
bundle install
exec bundle exec rake workers:collector:start[$1] --trace MONGOLAB_URI_DEVELOPMENT=$MONGOLAB_URI_DEVELOPMENT
