#!/bin/bash
\# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then

    \# First try to load from a user install
      source "$HOME/.rvm/scripts/rvm"

      elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then

        \# Then try to load from a root install
          source "/usr/local/rvm/scripts/rvm"

          else

              printf "ERROR: An RVM installation was not found.\n"

              fi
cd server
source .rvmrc
bundle install
exec bundle exec rake workers:collector:start[$1] --trace MONGOLAB_URI_DEVELOPMENT=$MONGOLAB_URI_DEVELOPMENT
