#!/bin/bash
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
fi

cd server
source .rvmrc
rvm info
bundle install
export MONGOLAB_URI_DEVELOPMENT=$MONGOLAB_URI_DEVELOPMENT
exec bundle exec rails server -p $1
